version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: nargata_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: nargata
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nargata_db
    ports:
      - '5432:5432'
    volumes:
      - nargata_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U nargata -d nargata_db']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  nargata_pgdata:
    driver: local
